services:
    _defaults:
        autoconfigure: false
        autowiring: false

    memo_dev.listener.kernel:
        class: Memo\DevBundle\EventListener\HookListener
        arguments:
            - '@logger'
        tags: ['terminal42_service_annotation']
    
    memo_dev.hook_listener:
        class: Memo\DevBundle\Service\HookListener