services:
    _defaults:
        autowire: true
        autoconfigure: true
    Memo\DevBundle\EventListener\GeneratePageListener: ~
    Memo\DevBundle\EventListener\ParseBackendTemplateListener: ~
    Memo\DevBundle\EventListener\ParseFrontendTemplateListener:
        arguments:
            $framework: '@contao.framework'
        tags:
            - { name: contao.hook, hook: parseFrontendTemplate }
        public: true
    Memo\DevBundle\EventListener\DataContainer\SaveDevSettingsCallback:
        tags:
            - { name: contao.callback, table: tl_settings, target: config.onsubmit, method: onSubmitCallback, priority: 100 }
        public: true
    Memo\DevBundle\EventSubscriber\KernelRequestSubscriber:
        arguments:
            $scopeMatcher: '@contao.routing.scope_matcher'
            $tokenStorage: '@security.token_storage'
            $router: '@router'
            $framework: '@contao.framework'
    memo.dev.pagebackendtemplatelistener:
        class: Memo\DevBundle\EventListener\ParseBackendTemplateListener
        public: true
